import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import { formatDate, formatRupees } from "@/lib/format";
import { formatMobile } from "@/lib/mobile";
import { monthLabel } from "@/lib/months";
import type { ReceiptView } from "@/server/payments";

// The PDF uses the built-in Helvetica font, so its text is English only.

const METHOD_LABELS = { cash: "Cash", bank: "Bank transfer", jazzcash: "JazzCash", easypaisa: "Easypaisa" } as const;

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#111827" },
  header: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderColor: "#d1d5db", paddingBottom: 12 },
  org: { fontSize: 16, fontFamily: "Helvetica-Bold" },
  muted: { color: "#6b7280" },
  number: { fontFamily: "Helvetica-Bold", textAlign: "right" },
  cancelled: { marginBottom: 12, padding: 8, backgroundColor: "#fee2e2", color: "#b91c1c" },
  details: { marginTop: 16, marginBottom: 16 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 110, color: "#6b7280" },
  table: { borderTopWidth: 1, borderColor: "#d1d5db" },
  tableRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderColor: "#e5e7eb" },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8, fontFamily: "Helvetica-Bold", fontSize: 13 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", color: "#9ca3af", fontSize: 9 },
});

/** Returns the <Document> element itself (renderToBuffer needs a Document, not a wrapper component). */
export function buildReceiptDocument(receipt: ReceiptView) {
  const household = receipt.household;
  return (
    <Document title={`Receipt ${receipt.receiptNumber}`} author={receipt.organisationName}>
      <Page size="A5" style={styles.page}>
        {receipt.status === "cancelled" ? (
          <View style={styles.cancelled}>
            <Text>CANCELLED{receipt.cancelReason ? `: ${receipt.cancelReason}` : ""}</Text>
          </View>
        ) : null}

        <View style={styles.header}>
          <View>
            <Text style={styles.org}>{receipt.organisationName}</Text>
            <Text style={styles.muted}>Street cleaning fee receipt</Text>
          </View>
          <View>
            <Text style={styles.number}>{receipt.receiptNumber}</Text>
            <Text style={styles.muted}>{formatDate(new Date(receipt.paidAt), "d MMM yyyy, h:mm a")}</Text>
          </View>
        </View>

        <View style={styles.details}>
          <View style={styles.row}>
            <Text style={styles.label}>Received from</Text>
            <Text>{household.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>House</Text>
            <Text>
              {household.houseNumber}, {household.streetName}, {household.blockName}, {household.areaName}
            </Text>
          </View>
          {household.mobile ? (
            <View style={styles.row}>
              <Text style={styles.label}>Mobile</Text>
              <Text>{formatMobile(household.mobile)}</Text>
            </View>
          ) : null}
          <View style={styles.row}>
            <Text style={styles.label}>Paid by</Text>
            <Text>{METHOD_LABELS[receipt.method]}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Received by</Text>
            <Text>{receipt.receivedBy}</Text>
          </View>
        </View>

        <View style={styles.table}>
          {receipt.allocations.map((allocation) => (
            <View key={allocation.month} style={styles.tableRow}>
              <Text>{monthLabel(allocation.month)}</Text>
              <Text>{formatRupees(allocation.amount)}</Text>
            </View>
          ))}
          <View style={styles.totalRow}>
            <Text>Total</Text>
            <Text>{formatRupees(receipt.amount)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Thank you for keeping our streets clean. This receipt was generated by Saaf Gali.</Text>
      </Page>
    </Document>
  );
}
